CREATE TABLE templates (
  id UUID PRIMARY KEY NOT NULL,
  user_id VARCHAR(30) REFERENCES users(id) NOT NULL,
  name VARCHAR(255) NOT NULL,
  json_data JSONB NOT NULL,
  html_content TEXT NOT NULL,
  attachments TEXT[],
  category VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);