CREATE TABLE user_tokens (
  id UUID PRIMARY KEY NOT NULL 
  user_id VARCHAR(30) REFERENCES users(id)  NOT NULL,
  google_token TEXT NOT NULL,  
  token_expiry TIMESTAMP WITH TIME ZONE NOT NULL,
  refresh_token TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);